---
apiVersion: v1
kind: Service
metadata:
  name: chroma-service
  namespace: kubeflow-rag
  labels:
    app: chroma
spec:
  selector:
    app: chroma
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
